### PR TITLE
Fix custom IMAGE marker

### LINKED ISSUE #149: Marker icon for custom tables broken when using "IMAGE"
When using something like 

```
plugin.tx_odsosm_pi1.icon {
    tt_address = IMAGE
    tt_address {
        file = EXT:...
    }
}
```

I get a PHP warning:

PHP Warning: Trying to access array offset on value of type null in /var/www/html/vendor/bobosch/ods-osm/Classes/Controller/PluginController.php line 543'

Even if the warnings would be tolerated, this would end in the follwoing error:

Call to a member function getPublicUrl() on null
/var/www/html/vendor/bobosch/ods-osm/Classes/Provider/Leaflet.php'
line: 294

The problem is the usage of $GLOBALS['TSFE']->lastImageInfo which got removed.

### PR DESCRIPTION
**Pull request by hannesbochmann**
fixes #149

### CODE REVIEW

**Comment by albig** [comment]
Thank you. Does this work with both 11.5 LTS and 12.4 LTS?

**Comment by albig** [comment]
Ok, so you tested with TYPO3 12.4 LTS?

**Comment by hannesbochmann** [comment]
Yes, my maps with tt_records worked again after this fix in TYPO3 12.4.

**Review by albig — APPROVED** [review]
Works for me with TYPO3 11.5 TLS and 12.4 LTS. Thank you!

**Pull request merged**
