### PR TITLE
[TASK] Delete MapSurfer.Net

### PR DESCRIPTION
**Pull request by simonschaufi**
They shut down their service in June 2020.

See https://ask.openrouteservice.org/t/mapsurfer-deprecation-cached-tiles-removed-after-june-2020/1704

### CODE REVIEW

**Comment by albig** [comment]
The records are already marked as deleted. Of course, we could purge theme completely, as you suggest.

**Comment by simonschaufi** [comment]
Let's keep the file clean ;) No need to import deleted records

**Comment by albig** [comment]
Not yet convinced. I continued the initial approach to disable old tile sources. Especially, you shouldn't touch the UIDs of the tile layer. This may lead to extra confusion if someone purge the layers and import it again, but the plugins just use the UID to select hte layer. That's all not perfect and I would like to  have a "Wizard" to update used layers, but for now, I don't see any advantage for this PR.

**Comment by simonschaufi** [comment]
The layers are actually hidden and NOT deleted. If they would be deleted, then it would be a different story. This service should not be possible to be activated anymore as it is completely shut down.

The uids will stay the same as you don't import NULL as uid.

**Comment by simonschaufi** [comment]
@albig What would be a reason to keep these records?

The uids will stay the same after another import as you don't import NULL as uid.

**Comment by bobosch** [comment]
The other uid's don't change, and nobody will have an non-working layer configured in the frontend plugin - so I think it is safe to remove them from the import file.

**Comment by bobosch** [comment]
@simonschaufi Thanks for your support!

**Comment by simonschaufi** [comment]
@bobosch can you have a look at my PRs and merge them?

**Pull request merged**
